In [1]:
import numpy as np

In [2]:
m1=np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
m2=np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [4]:
t= np.array([m1,m2])

In [5]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [6]:
t.shape

(2, 2, 3)

In [7]:
t_manual=np.array([[[5,12,6],[-3,0,14]],[[9,8,7],[1,3,-5]]])

In [8]:
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [9]:
m1+m2

array([[14, 20, 13],
       [-2,  3,  9]])

In [10]:
m1-m2

array([[-4,  4, -1],
       [-4, -3, 19]])

In [12]:
v1=np.array([1,2,3,4,5])
v2=np.array([5,4,3,2,1])

In [13]:
v1+v2

array([6, 6, 6, 6, 6])

In [14]:
v1-v2

array([-4, -2,  0,  2,  4])